name: Markdown Links Check
on:
  workflow_call:
    inputs:
      config-path:
        description: 'Path to the Linkspector configuration file'
        default: ''
        required: false
        type: string
jobs:
  markdown-links:
    name: Markdown Links Check
    runs-on: ubuntu-latest
    steps:
      - name: Harden runner
        uses: step-security/harden-runner@8d3c67de8e2fe68ef647c8db1e6a09f647780f40 # v2.19.0
        with:
          egress-policy: audit
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Check links in modified Markdown files
        if: inputs.config-path == ''
        uses: umbrelladocs/action-linkspector@963b6264d7de32c904942a70b488d3407453049e # v1.5.1
        with:
          fail_on_error: true
          filter_mode: file
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review
      - name: Check links in modified Markdown files with config file
        if: inputs.config-path != ''
        uses: umbrelladocs/action-linkspector@963b6264d7de32c904942a70b488d3407453049e # v1.5.1
        with:
          config_file: ${{ inputs.config-path }}
          fail_on_error: true
          filter_mode: file
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review
